export interface BRTeam {
  slug: string;
  label: string;
  sport: string;
  espnId: string; // used in ESPN RSS: espn.com/espn/rss/{espnLeague}/news?team={espnId}
  espnLeague: string; // nba | nfl | mlb | nhl | soccer
}

export const BR_TEAMS: BRTeam[] = [
  // NBA
  { slug: "atlanta-hawks",           label: "Atlanta Hawks",           sport: "NBA",    espnId: "atl",  espnLeague: "nba" },
  { slug: "boston-celtics",          label: "Boston Celtics",          sport: "NBA",    espnId: "bos",  espnLeague: "nba" },
  { slug: "brooklyn-nets",           label: "Brooklyn Nets",           sport: "NBA",    espnId: "bkn",  espnLeague: "nba" },
  { slug: "charlotte-hornets",       label: "Charlotte Hornets",       sport: "NBA",    espnId: "cha",  espnLeague: "nba" },
  { slug: "chicago-bulls",           label: "Chicago Bulls",           sport: "NBA",    espnId: "chi",  espnLeague: "nba" },
  { slug: "cleveland-cavaliers",     label: "Cleveland Cavaliers",     sport: "NBA",    espnId: "cle",  espnLeague: "nba" },
  { slug: "dallas-mavericks",        label: "Dallas Mavericks",        sport: "NBA",    espnId: "dal",  espnLeague: "nba" },
  { slug: "denver-nuggets",          label: "Denver Nuggets",          sport: "NBA",    espnId: "den",  espnLeague: "nba" },
  { slug: "detroit-pistons",         label: "Detroit Pistons",         sport: "NBA",    espnId: "det",  espnLeague: "nba" },
  { slug: "golden-state-warriors",   label: "Golden State Warriors",   sport: "NBA",    espnId: "gs",   espnLeague: "nba" },
  { slug: "houston-rockets",         label: "Houston Rockets",         sport: "NBA",    espnId: "hou",  espnLeague: "nba" },
  { slug: "indiana-pacers",          label: "Indiana Pacers",          sport: "NBA",    espnId: "ind",  espnLeague: "nba" },
  { slug: "los-angeles-clippers",    label: "LA Clippers",             sport: "NBA",    espnId: "lac",  espnLeague: "nba" },
  { slug: "los-angeles-lakers",      label: "LA Lakers",               sport: "NBA",    espnId: "lal",  espnLeague: "nba" },
  { slug: "memphis-grizzlies",       label: "Memphis Grizzlies",       sport: "NBA",    espnId: "mem",  espnLeague: "nba" },
  { slug: "miami-heat",              label: "Miami Heat",              sport: "NBA",    espnId: "mia",  espnLeague: "nba" },
  { slug: "milwaukee-bucks",         label: "Milwaukee Bucks",         sport: "NBA",    espnId: "mil",  espnLeague: "nba" },
  { slug: "minnesota-timberwolves",  label: "Minnesota Timberwolves",  sport: "NBA",    espnId: "min",  espnLeague: "nba" },
  { slug: "new-orleans-pelicans",    label: "New Orleans Pelicans",    sport: "NBA",    espnId: "no",   espnLeague: "nba" },
  { slug: "new-york-knicks",         label: "New York Knicks",         sport: "NBA",    espnId: "ny",   espnLeague: "nba" },
  { slug: "oklahoma-city-thunder",   label: "OKC Thunder",             sport: "NBA",    espnId: "okc",  espnLeague: "nba" },
  { slug: "orlando-magic",           label: "Orlando Magic",           sport: "NBA",    espnId: "orl",  espnLeague: "nba" },
  { slug: "philadelphia-76ers",      label: "Philadelphia 76ers",      sport: "NBA",    espnId: "phi",  espnLeague: "nba" },
  { slug: "phoenix-suns",            label: "Phoenix Suns",            sport: "NBA",    espnId: "phx",  espnLeague: "nba" },
  { slug: "portland-trail-blazers",  label: "Portland Trail Blazers",  sport: "NBA",    espnId: "por",  espnLeague: "nba" },
  { slug: "sacramento-kings",        label: "Sacramento Kings",        sport: "NBA",    espnId: "sac",  espnLeague: "nba" },
  { slug: "san-antonio-spurs",       label: "San Antonio Spurs",       sport: "NBA",    espnId: "sa",   espnLeague: "nba" },
  { slug: "toronto-raptors",         label: "Toronto Raptors",         sport: "NBA",    espnId: "tor",  espnLeague: "nba" },
  { slug: "utah-jazz",               label: "Utah Jazz",               sport: "NBA",    espnId: "utah", espnLeague: "nba" },
  { slug: "washington-wizards",      label: "Washington Wizards",      sport: "NBA",    espnId: "wsh",  espnLeague: "nba" },
  // NFL
  { slug: "arizona-cardinals",       label: "Arizona Cardinals",       sport: "NFL",    espnId: "ari",  espnLeague: "nfl" },
  { slug: "atlanta-falcons",         label: "Atlanta Falcons",         sport: "NFL",    espnId: "atl",  espnLeague: "nfl" },
  { slug: "baltimore-ravens",        label: "Baltimore Ravens",        sport: "NFL",    espnId: "bal",  espnLeague: "nfl" },
  { slug: "buffalo-bills",           label: "Buffalo Bills",           sport: "NFL",    espnId: "buf",  espnLeague: "nfl" },
  { slug: "carolina-panthers",       label: "Carolina Panthers",       sport: "NFL",    espnId: "car",  espnLeague: "nfl" },
  { slug: "chicago-bears",           label: "Chicago Bears",           sport: "NFL",    espnId: "chi",  espnLeague: "nfl" },
  { slug: "cincinnati-bengals",      label: "Cincinnati Bengals",      sport: "NFL",    espnId: "cin",  espnLeague: "nfl" },
  { slug: "cleveland-browns",        label: "Cleveland Browns",        sport: "NFL",    espnId: "cle",  espnLeague: "nfl" },
  { slug: "dallas-cowboys",          label: "Dallas Cowboys",          sport: "NFL",    espnId: "dal",  espnLeague: "nfl" },
  { slug: "denver-broncos",          label: "Denver Broncos",          sport: "NFL",    espnId: "den",  espnLeague: "nfl" },
  { slug: "detroit-lions",           label: "Detroit Lions",           sport: "NFL",    espnId: "det",  espnLeague: "nfl" },
  { slug: "green-bay-packers",       label: "Green Bay Packers",       sport: "NFL",    espnId: "gb",   espnLeague: "nfl" },
  { slug: "houston-texans",          label: "Houston Texans",          sport: "NFL",    espnId: "hou",  espnLeague: "nfl" },
  { slug: "indianapolis-colts",      label: "Indianapolis Colts",      sport: "NFL",    espnId: "ind",  espnLeague: "nfl" },
  { slug: "jacksonville-jaguars",    label: "Jacksonville Jaguars",    sport: "NFL",    espnId: "jac",  espnLeague: "nfl" },
  { slug: "kansas-city-chiefs",      label: "Kansas City Chiefs",      sport: "NFL",    espnId: "kc",   espnLeague: "nfl" },
  { slug: "las-vegas-raiders",       label: "Las Vegas Raiders",       sport: "NFL",    espnId: "lv",   espnLeague: "nfl" },
  { slug: "los-angeles-chargers",    label: "LA Chargers",             sport: "NFL",    espnId: "lac",  espnLeague: "nfl" },
  { slug: "los-angeles-rams",        label: "LA Rams",                 sport: "NFL",    espnId: "lar",  espnLeague: "nfl" },
  { slug: "miami-dolphins",          label: "Miami Dolphins",          sport: "NFL",    espnId: "mia",  espnLeague: "nfl" },
  { slug: "minnesota-vikings",       label: "Minnesota Vikings",       sport: "NFL",    espnId: "min",  espnLeague: "nfl" },
  { slug: "new-england-patriots",    label: "New England Patriots",    sport: "NFL",    espnId: "ne",   espnLeague: "nfl" },
  { slug: "new-orleans-saints",      label: "New Orleans Saints",      sport: "NFL",    espnId: "no",   espnLeague: "nfl" },
  { slug: "new-york-giants",         label: "New York Giants",         sport: "NFL",    espnId: "nyg",  espnLeague: "nfl" },
  { slug: "new-york-jets",           label: "New York Jets",           sport: "NFL",    espnId: "nyj",  espnLeague: "nfl" },
  { slug: "philadelphia-eagles",     label: "Philadelphia Eagles",     sport: "NFL",    espnId: "phi",  espnLeague: "nfl" },
  { slug: "pittsburgh-steelers",     label: "Pittsburgh Steelers",     sport: "NFL",    espnId: "pit",  espnLeague: "nfl" },
  { slug: "san-francisco-49ers",     label: "San Francisco 49ers",     sport: "NFL",    espnId: "sf",   espnLeague: "nfl" },
  { slug: "seattle-seahawks",        label: "Seattle Seahawks",        sport: "NFL",    espnId: "sea",  espnLeague: "nfl" },
  { slug: "tampa-bay-buccaneers",    label: "Tampa Bay Buccaneers",    sport: "NFL",    espnId: "tb",   espnLeague: "nfl" },
  { slug: "tennessee-titans",        label: "Tennessee Titans",        sport: "NFL",    espnId: "ten",  espnLeague: "nfl" },
  { slug: "washington-commanders",   label: "Washington Commanders",   sport: "NFL",    espnId: "wsh",  espnLeague: "nfl" },
  // MLB
  { slug: "arizona-diamondbacks",    label: "Arizona Diamondbacks",    sport: "MLB",    espnId: "ari",  espnLeague: "mlb" },
  { slug: "atlanta-braves",          label: "Atlanta Braves",          sport: "MLB",    espnId: "atl",  espnLeague: "mlb" },
  { slug: "baltimore-orioles",       label: "Baltimore Orioles",       sport: "MLB",    espnId: "bal",  espnLeague: "mlb" },
  { slug: "boston-red-sox",          label: "Boston Red Sox",          sport: "MLB",    espnId: "bos",  espnLeague: "mlb" },
  { slug: "chicago-cubs",            label: "Chicago Cubs",            sport: "MLB",    espnId: "chc",  espnLeague: "mlb" },
  { slug: "chicago-white-sox",       label: "Chicago White Sox",       sport: "MLB",    espnId: "cws",  espnLeague: "mlb" },
  { slug: "cincinnati-reds",         label: "Cincinnati Reds",         sport: "MLB",    espnId: "cin",  espnLeague: "mlb" },
  { slug: "cleveland-guardians",     label: "Cleveland Guardians",     sport: "MLB",    espnId: "cle",  espnLeague: "mlb" },
  { slug: "colorado-rockies",        label: "Colorado Rockies",        sport: "MLB",    espnId: "col",  espnLeague: "mlb" },
  { slug: "detroit-tigers",          label: "Detroit Tigers",          sport: "MLB",    espnId: "det",  espnLeague: "mlb" },
  { slug: "houston-astros",          label: "Houston Astros",          sport: "MLB",    espnId: "hou",  espnLeague: "mlb" },
  { slug: "kansas-city-royals",      label: "Kansas City Royals",      sport: "MLB",    espnId: "kc",   espnLeague: "mlb" },
  { slug: "los-angeles-angels",      label: "LA Angels",               sport: "MLB",    espnId: "laa",  espnLeague: "mlb" },
  { slug: "los-angeles-dodgers",     label: "LA Dodgers",              sport: "MLB",    espnId: "lad",  espnLeague: "mlb" },
  { slug: "miami-marlins",           label: "Miami Marlins",           sport: "MLB",    espnId: "mia",  espnLeague: "mlb" },
  { slug: "milwaukee-brewers",       label: "Milwaukee Brewers",       sport: "MLB",    espnId: "mil",  espnLeague: "mlb" },
  { slug: "minnesota-twins",         label: "Minnesota Twins",         sport: "MLB",    espnId: "min",  espnLeague: "mlb" },
  { slug: "new-york-mets",           label: "New York Mets",           sport: "MLB",    espnId: "nym",  espnLeague: "mlb" },
  { slug: "new-york-yankees",        label: "New York Yankees",        sport: "MLB",    espnId: "nyy",  espnLeague: "mlb" },
  { slug: "oakland-athletics",       label: "Oakland Athletics",       sport: "MLB",    espnId: "oak",  espnLeague: "mlb" },
  { slug: "philadelphia-phillies",   label: "Philadelphia Phillies",   sport: "MLB",    espnId: "phi",  espnLeague: "mlb" },
  { slug: "pittsburgh-pirates",      label: "Pittsburgh Pirates",      sport: "MLB",    espnId: "pit",  espnLeague: "mlb" },
  { slug: "san-diego-padres",        label: "San Diego Padres",        sport: "MLB",    espnId: "sd",   espnLeague: "mlb" },
  { slug: "san-francisco-giants",    label: "San Francisco Giants",    sport: "MLB",    espnId: "sf",   espnLeague: "mlb" },
  { slug: "seattle-mariners",        label: "Seattle Mariners",        sport: "MLB",    espnId: "sea",  espnLeague: "mlb" },
  { slug: "st-louis-cardinals",      label: "St. Louis Cardinals",     sport: "MLB",    espnId: "stl",  espnLeague: "mlb" },
  { slug: "tampa-bay-rays",          label: "Tampa Bay Rays",          sport: "MLB",    espnId: "tb",   espnLeague: "mlb" },
  { slug: "texas-rangers",           label: "Texas Rangers",           sport: "MLB",    espnId: "tex",  espnLeague: "mlb" },
  { slug: "toronto-blue-jays",       label: "Toronto Blue Jays",       sport: "MLB",    espnId: "tor",  espnLeague: "mlb" },
  { slug: "washington-nationals",    label: "Washington Nationals",    sport: "MLB",    espnId: "wsh",  espnLeague: "mlb" },
  // NHL
  { slug: "anaheim-ducks",           label: "Anaheim Ducks",           sport: "NHL",    espnId: "ana",  espnLeague: "nhl" },
  { slug: "boston-bruins",           label: "Boston Bruins",           sport: "NHL",    espnId: "bos",  espnLeague: "nhl" },
  { slug: "buffalo-sabres",          label: "Buffalo Sabres",          sport: "NHL",    espnId: "buf",  espnLeague: "nhl" },
  { slug: "calgary-flames",          label: "Calgary Flames",          sport: "NHL",    espnId: "cgy",  espnLeague: "nhl" },
  { slug: "carolina-hurricanes",     label: "Carolina Hurricanes",     sport: "NHL",    espnId: "car",  espnLeague: "nhl" },
  { slug: "chicago-blackhawks",      label: "Chicago Blackhawks",      sport: "NHL",    espnId: "chi",  espnLeague: "nhl" },
  { slug: "colorado-avalanche",      label: "Colorado Avalanche",      sport: "NHL",    espnId: "col",  espnLeague: "nhl" },
  { slug: "columbus-blue-jackets",   label: "Columbus Blue Jackets",   sport: "NHL",    espnId: "cbj",  espnLeague: "nhl" },
  { slug: "dallas-stars",            label: "Dallas Stars",            sport: "NHL",    espnId: "dal",  espnLeague: "nhl" },
  { slug: "detroit-red-wings",       label: "Detroit Red Wings",       sport: "NHL",    espnId: "det",  espnLeague: "nhl" },
  { slug: "edmonton-oilers",         label: "Edmonton Oilers",         sport: "NHL",    espnId: "edm",  espnLeague: "nhl" },
  { slug: "florida-panthers",        label: "Florida Panthers",        sport: "NHL",    espnId: "fla",  espnLeague: "nhl" },
  { slug: "los-angeles-kings",       label: "LA Kings",                sport: "NHL",    espnId: "lak",  espnLeague: "nhl" },
  { slug: "minnesota-wild",          label: "Minnesota Wild",          sport: "NHL",    espnId: "min",  espnLeague: "nhl" },
  { slug: "montreal-canadiens",      label: "Montreal Canadiens",      sport: "NHL",    espnId: "mtl",  espnLeague: "nhl" },
  { slug: "nashville-predators",     label: "Nashville Predators",     sport: "NHL",    espnId: "nsh",  espnLeague: "nhl" },
  { slug: "new-jersey-devils",       label: "New Jersey Devils",       sport: "NHL",    espnId: "njd",  espnLeague: "nhl" },
  { slug: "new-york-islanders",      label: "New York Islanders",      sport: "NHL",    espnId: "nyi",  espnLeague: "nhl" },
  { slug: "new-york-rangers",        label: "New York Rangers",        sport: "NHL",    espnId: "nyr",  espnLeague: "nhl" },
  { slug: "ottawa-senators",         label: "Ottawa Senators",         sport: "NHL",    espnId: "ott",  espnLeague: "nhl" },
  { slug: "philadelphia-flyers",     label: "Philadelphia Flyers",     sport: "NHL",    espnId: "phi",  espnLeague: "nhl" },
  { slug: "pittsburgh-penguins",     label: "Pittsburgh Penguins",     sport: "NHL",    espnId: "pit",  espnLeague: "nhl" },
  { slug: "san-jose-sharks",         label: "San Jose Sharks",         sport: "NHL",    espnId: "sj",   espnLeague: "nhl" },
  { slug: "seattle-kraken",          label: "Seattle Kraken",          sport: "NHL",    espnId: "sea",  espnLeague: "nhl" },
  { slug: "st-louis-blues",          label: "St. Louis Blues",         sport: "NHL",    espnId: "stl",  espnLeague: "nhl" },
  { slug: "tampa-bay-lightning",     label: "Tampa Bay Lightning",     sport: "NHL",    espnId: "tb",   espnLeague: "nhl" },
  { slug: "toronto-maple-leafs",     label: "Toronto Maple Leafs",     sport: "NHL",    espnId: "tor",  espnLeague: "nhl" },
  { slug: "utah-hockey-club",        label: "Utah Hockey Club",        sport: "NHL",    espnId: "uta",  espnLeague: "nhl" },
  { slug: "vancouver-canucks",       label: "Vancouver Canucks",       sport: "NHL",    espnId: "van",  espnLeague: "nhl" },
  { slug: "vegas-golden-knights",    label: "Vegas Golden Knights",    sport: "NHL",    espnId: "vgk",  espnLeague: "nhl" },
  { slug: "washington-capitals",     label: "Washington Capitals",     sport: "NHL",    espnId: "wsh",  espnLeague: "nhl" },
  { slug: "winnipeg-jets",           label: "Winnipeg Jets",           sport: "NHL",    espnId: "wpg",  espnLeague: "nhl" },
  // Soccer
  { slug: "fc-barcelona",            label: "FC Barcelona",            sport: "Soccer", espnId: "bar",  espnLeague: "soccer" },
  { slug: "real-madrid",             label: "Real Madrid",             sport: "Soccer", espnId: "rma",  espnLeague: "soccer" },
  { slug: "manchester-united",       label: "Manchester United",       sport: "Soccer", espnId: "mun",  espnLeague: "soccer" },
  { slug: "manchester-city",         label: "Manchester City",         sport: "Soccer", espnId: "mci",  espnLeague: "soccer" },
  { slug: "liverpool-fc",            label: "Liverpool",               sport: "Soccer", espnId: "liv",  espnLeague: "soccer" },
  { slug: "chelsea-fc",              label: "Chelsea",                 sport: "Soccer", espnId: "che",  espnLeague: "soccer" },
  { slug: "arsenal-fc",              label: "Arsenal",                 sport: "Soccer", espnId: "ars",  espnLeague: "soccer" },
  { slug: "tottenham-hotspur",       label: "Tottenham Hotspur",       sport: "Soccer", espnId: "tot",  espnLeague: "soccer" },
  { slug: "juventus-fc",             label: "Juventus",                sport: "Soccer", espnId: "juv",  espnLeague: "soccer" },
  { slug: "paris-saint-germain",     label: "PSG",                     sport: "Soccer", espnId: "psg",  espnLeague: "soccer" },
  { slug: "us-soccer",               label: "USMNT",                   sport: "Soccer", espnId: "usa",  espnLeague: "soccer" },
];

export const DEFAULT_BR_TEAMS: string[] = [];
export const DEFAULT_TWITTER_ACCOUNTS: string[] = [];

export const NITTER_INSTANCES = [
  "https://nitter.privacydev.net",
  "https://nitter.poast.org",
  "https://nitter.1d4.us",
  "https://nitter.unixfox.eu",
];

export const DAYS_SHOWN = 7;
export const REFRESH_INTERVAL_MS = 15 * 60 * 1000;
