export interface BRTeam {
  slug: string;
  label: string;
  sport: string;
}

export const BR_TEAMS: BRTeam[] = [
  // NBA
  { slug: "atlanta-hawks", label: "Atlanta Hawks", sport: "NBA" },
  { slug: "boston-celtics", label: "Boston Celtics", sport: "NBA" },
  { slug: "brooklyn-nets", label: "Brooklyn Nets", sport: "NBA" },
  { slug: "charlotte-hornets", label: "Charlotte Hornets", sport: "NBA" },
  { slug: "chicago-bulls", label: "Chicago Bulls", sport: "NBA" },
  { slug: "cleveland-cavaliers", label: "Cleveland Cavaliers", sport: "NBA" },
  { slug: "dallas-mavericks", label: "Dallas Mavericks", sport: "NBA" },
  { slug: "denver-nuggets", label: "Denver Nuggets", sport: "NBA" },
  { slug: "detroit-pistons", label: "Detroit Pistons", sport: "NBA" },
  { slug: "golden-state-warriors", label: "Golden State Warriors", sport: "NBA" },
  { slug: "houston-rockets", label: "Houston Rockets", sport: "NBA" },
  { slug: "indiana-pacers", label: "Indiana Pacers", sport: "NBA" },
  { slug: "los-angeles-clippers", label: "LA Clippers", sport: "NBA" },
  { slug: "los-angeles-lakers", label: "LA Lakers", sport: "NBA" },
  { slug: "memphis-grizzlies", label: "Memphis Grizzlies", sport: "NBA" },
  { slug: "miami-heat", label: "Miami Heat", sport: "NBA" },
  { slug: "milwaukee-bucks", label: "Milwaukee Bucks", sport: "NBA" },
  { slug: "minnesota-timberwolves", label: "Minnesota Timberwolves", sport: "NBA" },
  { slug: "new-orleans-pelicans", label: "New Orleans Pelicans", sport: "NBA" },
  { slug: "new-york-knicks", label: "New York Knicks", sport: "NBA" },
  { slug: "oklahoma-city-thunder", label: "OKC Thunder", sport: "NBA" },
  { slug: "orlando-magic", label: "Orlando Magic", sport: "NBA" },
  { slug: "philadelphia-76ers", label: "Philadelphia 76ers", sport: "NBA" },
  { slug: "phoenix-suns", label: "Phoenix Suns", sport: "NBA" },
  { slug: "portland-trail-blazers", label: "Portland Trail Blazers", sport: "NBA" },
  { slug: "sacramento-kings", label: "Sacramento Kings", sport: "NBA" },
  { slug: "san-antonio-spurs", label: "San Antonio Spurs", sport: "NBA" },
  { slug: "toronto-raptors", label: "Toronto Raptors", sport: "NBA" },
  { slug: "utah-jazz", label: "Utah Jazz", sport: "NBA" },
  { slug: "washington-wizards", label: "Washington Wizards", sport: "NBA" },
  // NFL
  { slug: "arizona-cardinals", label: "Arizona Cardinals", sport: "NFL" },
  { slug: "atlanta-falcons", label: "Atlanta Falcons", sport: "NFL" },
  { slug: "baltimore-ravens", label: "Baltimore Ravens", sport: "NFL" },
  { slug: "buffalo-bills", label: "Buffalo Bills", sport: "NFL" },
  { slug: "carolina-panthers", label: "Carolina Panthers", sport: "NFL" },
  { slug: "chicago-bears", label: "Chicago Bears", sport: "NFL" },
  { slug: "cincinnati-bengals", label: "Cincinnati Bengals", sport: "NFL" },
  { slug: "cleveland-browns", label: "Cleveland Browns", sport: "NFL" },
  { slug: "dallas-cowboys", label: "Dallas Cowboys", sport: "NFL" },
  { slug: "denver-broncos", label: "Denver Broncos", sport: "NFL" },
  { slug: "detroit-lions", label: "Detroit Lions", sport: "NFL" },
  { slug: "green-bay-packers", label: "Green Bay Packers", sport: "NFL" },
  { slug: "houston-texans", label: "Houston Texans", sport: "NFL" },
  { slug: "indianapolis-colts", label: "Indianapolis Colts", sport: "NFL" },
  { slug: "jacksonville-jaguars", label: "Jacksonville Jaguars", sport: "NFL" },
  { slug: "kansas-city-chiefs", label: "Kansas City Chiefs", sport: "NFL" },
  { slug: "las-vegas-raiders", label: "Las Vegas Raiders", sport: "NFL" },
  { slug: "los-angeles-chargers", label: "LA Chargers", sport: "NFL" },
  { slug: "los-angeles-rams", label: "LA Rams", sport: "NFL" },
  { slug: "miami-dolphins", label: "Miami Dolphins", sport: "NFL" },
  { slug: "minnesota-vikings", label: "Minnesota Vikings", sport: "NFL" },
  { slug: "new-england-patriots", label: "New England Patriots", sport: "NFL" },
  { slug: "new-orleans-saints", label: "New Orleans Saints", sport: "NFL" },
  { slug: "new-york-giants", label: "New York Giants", sport: "NFL" },
  { slug: "new-york-jets", label: "New York Jets", sport: "NFL" },
  { slug: "philadelphia-eagles", label: "Philadelphia Eagles", sport: "NFL" },
  { slug: "pittsburgh-steelers", label: "Pittsburgh Steelers", sport: "NFL" },
  { slug: "san-francisco-49ers", label: "San Francisco 49ers", sport: "NFL" },
  { slug: "seattle-seahawks", label: "Seattle Seahawks", sport: "NFL" },
  { slug: "tampa-bay-buccaneers", label: "Tampa Bay Buccaneers", sport: "NFL" },
  { slug: "tennessee-titans", label: "Tennessee Titans", sport: "NFL" },
  { slug: "washington-commanders", label: "Washington Commanders", sport: "NFL" },
  // MLB
  { slug: "arizona-diamondbacks", label: "Arizona Diamondbacks", sport: "MLB" },
  { slug: "atlanta-braves", label: "Atlanta Braves", sport: "MLB" },
  { slug: "baltimore-orioles", label: "Baltimore Orioles", sport: "MLB" },
  { slug: "boston-red-sox", label: "Boston Red Sox", sport: "MLB" },
  { slug: "chicago-cubs", label: "Chicago Cubs", sport: "MLB" },
  { slug: "chicago-white-sox", label: "Chicago White Sox", sport: "MLB" },
  { slug: "cincinnati-reds", label: "Cincinnati Reds", sport: "MLB" },
  { slug: "cleveland-guardians", label: "Cleveland Guardians", sport: "MLB" },
  { slug: "colorado-rockies", label: "Colorado Rockies", sport: "MLB" },
  { slug: "detroit-tigers", label: "Detroit Tigers", sport: "MLB" },
  { slug: "houston-astros", label: "Houston Astros", sport: "MLB" },
  { slug: "kansas-city-royals", label: "Kansas City Royals", sport: "MLB" },
  { slug: "los-angeles-angels", label: "LA Angels", sport: "MLB" },
  { slug: "los-angeles-dodgers", label: "LA Dodgers", sport: "MLB" },
  { slug: "miami-marlins", label: "Miami Marlins", sport: "MLB" },
  { slug: "milwaukee-brewers", label: "Milwaukee Brewers", sport: "MLB" },
  { slug: "minnesota-twins", label: "Minnesota Twins", sport: "MLB" },
  { slug: "new-york-mets", label: "New York Mets", sport: "MLB" },
  { slug: "new-york-yankees", label: "New York Yankees", sport: "MLB" },
  { slug: "oakland-athletics", label: "Oakland Athletics", sport: "MLB" },
  { slug: "philadelphia-phillies", label: "Philadelphia Phillies", sport: "MLB" },
  { slug: "pittsburgh-pirates", label: "Pittsburgh Pirates", sport: "MLB" },
  { slug: "san-diego-padres", label: "San Diego Padres", sport: "MLB" },
  { slug: "san-francisco-giants", label: "San Francisco Giants", sport: "MLB" },
  { slug: "seattle-mariners", label: "Seattle Mariners", sport: "MLB" },
  { slug: "st-louis-cardinals", label: "St. Louis Cardinals", sport: "MLB" },
  { slug: "tampa-bay-rays", label: "Tampa Bay Rays", sport: "MLB" },
  { slug: "texas-rangers", label: "Texas Rangers", sport: "MLB" },
  { slug: "toronto-blue-jays", label: "Toronto Blue Jays", sport: "MLB" },
  { slug: "washington-nationals", label: "Washington Nationals", sport: "MLB" },
  // NHL
  { slug: "anaheim-ducks", label: "Anaheim Ducks", sport: "NHL" },
  { slug: "boston-bruins", label: "Boston Bruins", sport: "NHL" },
  { slug: "buffalo-sabres", label: "Buffalo Sabres", sport: "NHL" },
  { slug: "calgary-flames", label: "Calgary Flames", sport: "NHL" },
  { slug: "carolina-hurricanes", label: "Carolina Hurricanes", sport: "NHL" },
  { slug: "chicago-blackhawks", label: "Chicago Blackhawks", sport: "NHL" },
  { slug: "colorado-avalanche", label: "Colorado Avalanche", sport: "NHL" },
  { slug: "columbus-blue-jackets", label: "Columbus Blue Jackets", sport: "NHL" },
  { slug: "dallas-stars", label: "Dallas Stars", sport: "NHL" },
  { slug: "detroit-red-wings", label: "Detroit Red Wings", sport: "NHL" },
  { slug: "edmonton-oilers", label: "Edmonton Oilers", sport: "NHL" },
  { slug: "florida-panthers", label: "Florida Panthers", sport: "NHL" },
  { slug: "los-angeles-kings", label: "LA Kings", sport: "NHL" },
  { slug: "minnesota-wild", label: "Minnesota Wild", sport: "NHL" },
  { slug: "montreal-canadiens", label: "Montreal Canadiens", sport: "NHL" },
  { slug: "nashville-predators", label: "Nashville Predators", sport: "NHL" },
  { slug: "new-jersey-devils", label: "New Jersey Devils", sport: "NHL" },
  { slug: "new-york-islanders", label: "New York Islanders", sport: "NHL" },
  { slug: "new-york-rangers", label: "New York Rangers", sport: "NHL" },
  { slug: "ottawa-senators", label: "Ottawa Senators", sport: "NHL" },
  { slug: "philadelphia-flyers", label: "Philadelphia Flyers", sport: "NHL" },
  { slug: "pittsburgh-penguins", label: "Pittsburgh Penguins", sport: "NHL" },
  { slug: "san-jose-sharks", label: "San Jose Sharks", sport: "NHL" },
  { slug: "seattle-kraken", label: "Seattle Kraken", sport: "NHL" },
  { slug: "st-louis-blues", label: "St. Louis Blues", sport: "NHL" },
  { slug: "tampa-bay-lightning", label: "Tampa Bay Lightning", sport: "NHL" },
  { slug: "toronto-maple-leafs", label: "Toronto Maple Leafs", sport: "NHL" },
  { slug: "utah-hockey-club", label: "Utah Hockey Club", sport: "NHL" },
  { slug: "vancouver-canucks", label: "Vancouver Canucks", sport: "NHL" },
  { slug: "vegas-golden-knights", label: "Vegas Golden Knights", sport: "NHL" },
  { slug: "washington-capitals", label: "Washington Capitals", sport: "NHL" },
  { slug: "winnipeg-jets", label: "Winnipeg Jets", sport: "NHL" },
  // Soccer
  { slug: "fc-barcelona", label: "FC Barcelona", sport: "Soccer" },
  { slug: "real-madrid", label: "Real Madrid", sport: "Soccer" },
  { slug: "manchester-united", label: "Manchester United", sport: "Soccer" },
  { slug: "manchester-city", label: "Manchester City", sport: "Soccer" },
  { slug: "liverpool-fc", label: "Liverpool", sport: "Soccer" },
  { slug: "chelsea-fc", label: "Chelsea", sport: "Soccer" },
  { slug: "arsenal-fc", label: "Arsenal", sport: "Soccer" },
  { slug: "tottenham-hotspur", label: "Tottenham Hotspur", sport: "Soccer" },
  { slug: "juventus-fc", label: "Juventus", sport: "Soccer" },
  { slug: "paris-saint-germain", label: "PSG", sport: "Soccer" },
  { slug: "us-soccer", label: "USMNT", sport: "Soccer" },
];

export const DEFAULT_BR_TEAMS: string[] = [];
export const DEFAULT_TWITTER_ACCOUNTS: string[] = [];

export const NITTER_INSTANCES = [
  "https://nitter.privacydev.net",
  "https://nitter.poast.org",
  "https://nitter.1d4.us",
  "https://nitter.unixfox.eu",
];

export const DAYS_SHOWN = 7;
export const REFRESH_INTERVAL_MS = 15 * 60 * 1000; // 15 minutes
